[System_Config.Ethos_U85_SRAM_OSPI]
core_clock=400e6
axi0_port=Sram
axi1_port=Dram
Sram_clock_scale=1.0
Sram_ports_used=2
Sram_burst_length=32
Sram_read_latency=2
Sram_write_latency=2
Sram_max_reads=2
Sram_max_writes=2
Dram_clock_scale=0.052
Dram_burst_length=16
Dram_read_latency=54
Dram_write_latency=54
Dram_max_reads=2
Dram_max_writes=2

; -----------------------------------------------------------------------------
; Memory Mode

[Memory_Mode.Dedicated_Sram]
const_mem_area=Axi1
arena_mem_area=Axi1
cache_mem_area=Axi0
; Arm tend to use 384K. We could use a lot more
;arena_cache_size=2048576
arena_cache_size=393216
